# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afdab9150ca036d41edf59b10c3081cfecae401e9cfc18a46e022f5ce4bcb69d48eb14dcc2ae22d610b9bcb59e80903c18cd2b2514c3157230a1773a5800a3b6

test:
  secret_key_base: 765a383de8af805c7402c439527744fb2dc79c9408b9a8f8366d33d631273e2311f5ed16e2a9f9487805b843eaa9428da9637a7bd6176df108c581c74f2785d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
